version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - SERVICE_ENV=dev
      - SERVICE_NAME=message-sender
      - SERVICE_PORT=8080
      - LOG_LEVEL=DEBUG
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_DATABASE=message_sender_db
      - REDIS_URL=redis://redis:6380/0
      - NOTIFICATION_PROVIDER=mock
      - MESSAGES_AUTO_START=true
      - MESSAGES_INTERVAL=120
    networks:
      - app-network
    command: >
      sh -c "
        apk add --no-cache netcat-openbsd
        echo 'Waiting for PostgreSQL to be ready...'
        while ! nc -z postgres 5432; do sleep 1; done
        echo 'PostgreSQL is ready!'
        ./main
      "

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=message_sender_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  redis:
    image: redis:6-alpine
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: